BS_position: !!python/tuple
- 500.0
- 500.0
- 0.0
Lipschitz: 1.0
T_max: 1000
UAV_positions:
- !!python/tuple
  - 0.0
  - 0.0
  - 0.0
- !!python/tuple
  - 1000.0
  - 1000.0
  - 0.0
- !!python/tuple
  - 1000.0
  - 0.0
  - 0.0
bandwidth: 20000000.0
batch_size: 128
channel_type: AWGN
clients_per_round: 3
compression_ratio: 0.16666666666666666
dataset: cifar10
device: cuda:1
drop_percent: 0.1
eirp:
- 30.0
- 30.0
- 30.0
eta_los: 1.0
eval_every: 1
experiment:
  description: Federated Learning experiment using feddane on cifar10 dataset with
    jscc model
  name: feddane_cifar10_jscc
  timestamp: '20250618_222909'
freq_carrier:
- 2400000000.0
- 2400000000.0
- 2400000000.0
seed: 42
gamma: 0.9
gamma1: 0.1
global_accuracy: 0.1
inner_channel: 8
learning_rate: 1.0e-05
local_accuracy: 0.5
local_iterations: 30
min_lr: 1.0e-05
model: jscc
model_params_tuple: !!python/tuple
- 8
- AWGN
- 1
- 19
mu: 0
noise_power: -169
num_rounds: 500
optimizer: feddane
parallel: true
parallel_devices:
- cuda:0
- cuda:1
- cuda:2
scheduler_type: StepLR
snr: 19
step_size: 100
weight_decay: 0
